env:
  browser: true
  es2021: true
  jest: true
extends:
  - plugin:react/recommended
  - airbnb
  - prettier
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {
  "linebreak-style": 0,
  "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"]  }],
  "react/react-in-jsx-scope": "off",
  "import/prefer-default-export": "off",
  "react/function-component-definition": "off",
  "no-param-reassign": 0,
}
